#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbFiles
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="pFiles")]
	public partial class databaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAcceptors(Acceptors instance);
    partial void UpdateAcceptors(Acceptors instance);
    partial void DeleteAcceptors(Acceptors instance);
    partial void InsertAccepts(Accepts instance);
    partial void UpdateAccepts(Accepts instance);
    partial void DeleteAccepts(Accepts instance);
    partial void InsertCredentials(Credentials instance);
    partial void UpdateCredentials(Credentials instance);
    partial void DeleteCredentials(Credentials instance);
    partial void InsertDonors(Donors instance);
    partial void UpdateDonors(Donors instance);
    partial void DeleteDonors(Donors instance);
    partial void InsertDonates(Donates instance);
    partial void UpdateDonates(Donates instance);
    partial void DeleteDonates(Donates instance);
    #endregion
		
		public databaseDataContext() : 
				base(global::bbFiles.Properties.Settings.Default.pFilesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public databaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Acceptors> Acceptors
		{
			get
			{
				return this.GetTable<Acceptors>();
			}
		}
		
		public System.Data.Linq.Table<Accepts> Accepts
		{
			get
			{
				return this.GetTable<Accepts>();
			}
		}
		
		public System.Data.Linq.Table<Credentials> Credentials
		{
			get
			{
				return this.GetTable<Credentials>();
			}
		}
		
		public System.Data.Linq.Table<Donors> Donors
		{
			get
			{
				return this.GetTable<Donors>();
			}
		}
		
		public System.Data.Linq.Table<Donates> Donates
		{
			get
			{
				return this.GetTable<Donates>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Acceptors")]
	public partial class Acceptors : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AcceptorID;
		
		private string _AcceptorName;
		
		private string _Address;
		
		private string _Email;
		
		private System.Nullable<int> _PhoneNumber;
		
		private int _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAcceptorIDChanging(int value);
    partial void OnAcceptorIDChanged();
    partial void OnAcceptorNameChanging(string value);
    partial void OnAcceptorNameChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneNumberChanging(System.Nullable<int> value);
    partial void OnPhoneNumberChanged();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    #endregion
		
		public Acceptors()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptorID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int AcceptorID
		{
			get
			{
				return this._AcceptorID;
			}
			set
			{
				if ((this._AcceptorID != value))
				{
					this.OnAcceptorIDChanging(value);
					this.SendPropertyChanging();
					this._AcceptorID = value;
					this.SendPropertyChanged("AcceptorID");
					this.OnAcceptorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptorName", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string AcceptorName
		{
			get
			{
				return this._AcceptorName;
			}
			set
			{
				if ((this._AcceptorName != value))
				{
					this.OnAcceptorNameChanging(value);
					this.SendPropertyChanging();
					this._AcceptorName = value;
					this.SendPropertyChanged("AcceptorName");
					this.OnAcceptorNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Int")]
		public System.Nullable<int> PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int NOT NULL")]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Accepts")]
	public partial class Accepts : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _AcceptID;
		
		private int _AcceptorID;
		
		private int _DonateID;
		
		private System.DateTime _AcceptDate;
		
		private bool _Status;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAcceptIDChanging(int value);
    partial void OnAcceptIDChanged();
    partial void OnAcceptorIDChanging(int value);
    partial void OnAcceptorIDChanged();
    partial void OnDonateIDChanging(int value);
    partial void OnDonateIDChanged();
    partial void OnAcceptDateChanging(System.DateTime value);
    partial void OnAcceptDateChanged();
    partial void OnStatusChanging(bool value);
    partial void OnStatusChanged();
    #endregion
		
		public Accepts()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int AcceptID
		{
			get
			{
				return this._AcceptID;
			}
			set
			{
				if ((this._AcceptID != value))
				{
					this.OnAcceptIDChanging(value);
					this.SendPropertyChanging();
					this._AcceptID = value;
					this.SendPropertyChanged("AcceptID");
					this.OnAcceptIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptorID", DbType="Int NOT NULL")]
		public int AcceptorID
		{
			get
			{
				return this._AcceptorID;
			}
			set
			{
				if ((this._AcceptorID != value))
				{
					this.OnAcceptorIDChanging(value);
					this.SendPropertyChanging();
					this._AcceptorID = value;
					this.SendPropertyChanged("AcceptorID");
					this.OnAcceptorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonateID", DbType="Int NOT NULL")]
		public int DonateID
		{
			get
			{
				return this._DonateID;
			}
			set
			{
				if ((this._DonateID != value))
				{
					this.OnDonateIDChanging(value);
					this.SendPropertyChanging();
					this._DonateID = value;
					this.SendPropertyChanged("DonateID");
					this.OnDonateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AcceptDate", DbType="Date NOT NULL")]
		public System.DateTime AcceptDate
		{
			get
			{
				return this._AcceptDate;
			}
			set
			{
				if ((this._AcceptDate != value))
				{
					this.OnAcceptDateChanging(value);
					this.SendPropertyChanging();
					this._AcceptDate = value;
					this.SendPropertyChanged("AcceptDate");
					this.OnAcceptDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Bit NOT NULL")]
		public bool Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this.OnStatusChanging(value);
					this.SendPropertyChanging();
					this._Status = value;
					this.SendPropertyChanged("Status");
					this.OnStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Credentials")]
	public partial class Credentials : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Login;
		
		private string _Password;
		
		private bool _PasswordChanged;
		
		private System.DateTime _RegisteredDate;
		
		private System.Nullable<System.DateTime> _LastLoggedDate;
		
		private global::bbFiles.Roles _Role;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnLoginChanging(string value);
    partial void OnLoginChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnPasswordChangedChanging(bool value);
    partial void OnPasswordChangedChanged();
    partial void OnRegisteredDateChanging(System.DateTime value);
    partial void OnRegisteredDateChanged();
    partial void OnLastLoggedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLoggedDateChanged();
    partial void OnRoleChanging(global::bbFiles.Roles value);
    partial void OnRoleChanged();
    #endregion
		
		public Credentials()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Login
		{
			get
			{
				return this._Login;
			}
			set
			{
				if ((this._Login != value))
				{
					this.OnLoginChanging(value);
					this.SendPropertyChanging();
					this._Login = value;
					this.SendPropertyChanged("Login");
					this.OnLoginChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordChanged", DbType="Bit NOT NULL")]
		public bool PasswordChanged
		{
			get
			{
				return this._PasswordChanged;
			}
			set
			{
				if ((this._PasswordChanged != value))
				{
					this.OnPasswordChangedChanging(value);
					this.SendPropertyChanging();
					this._PasswordChanged = value;
					this.SendPropertyChanged("PasswordChanged");
					this.OnPasswordChangedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredDate", DbType="Date NOT NULL")]
		public System.DateTime RegisteredDate
		{
			get
			{
				return this._RegisteredDate;
			}
			set
			{
				if ((this._RegisteredDate != value))
				{
					this.OnRegisteredDateChanging(value);
					this.SendPropertyChanging();
					this._RegisteredDate = value;
					this.SendPropertyChanged("RegisteredDate");
					this.OnRegisteredDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastLoggedDate", DbType="Date")]
		public System.Nullable<System.DateTime> LastLoggedDate
		{
			get
			{
				return this._LastLoggedDate;
			}
			set
			{
				if ((this._LastLoggedDate != value))
				{
					this.OnLastLoggedDateChanging(value);
					this.SendPropertyChanging();
					this._LastLoggedDate = value;
					this.SendPropertyChanged("LastLoggedDate");
					this.OnLastLoggedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Role", DbType="TinyInt NOT NULL", CanBeNull=false)]
		public global::bbFiles.Roles Role
		{
			get
			{
				return this._Role;
			}
			set
			{
				if ((this._Role != value))
				{
					this.OnRoleChanging(value);
					this.SendPropertyChanging();
					this._Role = value;
					this.SendPropertyChanged("Role");
					this.OnRoleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Donors")]
	public partial class Donors : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Firstname;
		
		private string _Surname;
		
		private System.DateTime _Birthdate;
		
		private global::bbFiles.BloodTypes _BloodType;
		
		private bool _RhMarker;
		
		private double _BloodGiven;
		
		private long _PESEL;
		
		private string _Email;
		
		private System.Nullable<int> _PhoneNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFirstnameChanging(string value);
    partial void OnFirstnameChanged();
    partial void OnSurnameChanging(string value);
    partial void OnSurnameChanged();
    partial void OnBirthdateChanging(System.DateTime value);
    partial void OnBirthdateChanged();
    partial void OnBloodTypeChanging(global::bbFiles.BloodTypes value);
    partial void OnBloodTypeChanged();
    partial void OnRhMarkerChanging(bool value);
    partial void OnRhMarkerChanged();
    partial void OnBloodGivenChanging(double value);
    partial void OnBloodGivenChanged();
    partial void OnPESELChanging(long value);
    partial void OnPESELChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPhoneNumberChanging(System.Nullable<int> value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public Donors()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Firstname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Firstname
		{
			get
			{
				return this._Firstname;
			}
			set
			{
				if ((this._Firstname != value))
				{
					this.OnFirstnameChanging(value);
					this.SendPropertyChanging();
					this._Firstname = value;
					this.SendPropertyChanged("Firstname");
					this.OnFirstnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Surname", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Surname
		{
			get
			{
				return this._Surname;
			}
			set
			{
				if ((this._Surname != value))
				{
					this.OnSurnameChanging(value);
					this.SendPropertyChanging();
					this._Surname = value;
					this.SendPropertyChanged("Surname");
					this.OnSurnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthdate", DbType="Date NOT NULL")]
		public System.DateTime Birthdate
		{
			get
			{
				return this._Birthdate;
			}
			set
			{
				if ((this._Birthdate != value))
				{
					this.OnBirthdateChanging(value);
					this.SendPropertyChanging();
					this._Birthdate = value;
					this.SendPropertyChanged("Birthdate");
					this.OnBirthdateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodType", DbType="Int NOT NULL", CanBeNull=false)]
		public global::bbFiles.BloodTypes BloodType
		{
			get
			{
				return this._BloodType;
			}
			set
			{
				if ((this._BloodType != value))
				{
					this.OnBloodTypeChanging(value);
					this.SendPropertyChanging();
					this._BloodType = value;
					this.SendPropertyChanged("BloodType");
					this.OnBloodTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RhMarker", DbType="Bit NOT NULL")]
		public bool RhMarker
		{
			get
			{
				return this._RhMarker;
			}
			set
			{
				if ((this._RhMarker != value))
				{
					this.OnRhMarkerChanging(value);
					this.SendPropertyChanging();
					this._RhMarker = value;
					this.SendPropertyChanged("RhMarker");
					this.OnRhMarkerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodGiven", DbType="Float NOT NULL")]
		public double BloodGiven
		{
			get
			{
				return this._BloodGiven;
			}
			set
			{
				if ((this._BloodGiven != value))
				{
					this.OnBloodGivenChanging(value);
					this.SendPropertyChanging();
					this._BloodGiven = value;
					this.SendPropertyChanged("BloodGiven");
					this.OnBloodGivenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PESEL", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long PESEL
		{
			get
			{
				return this._PESEL;
			}
			set
			{
				if ((this._PESEL != value))
				{
					this.OnPESELChanging(value);
					this.SendPropertyChanging();
					this._PESEL = value;
					this.SendPropertyChanged("PESEL");
					this.OnPESELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoneNumber", DbType="Int")]
		public System.Nullable<int> PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Donates")]
	public partial class Donates : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DonateID;
		
		private int _Amount;
		
		private System.DateTime _Date;
		
		private global::bbFiles.BloodTypes _BloodType;
		
		private bool _RhMarker;
		
		private long _DonorPESEL;
		
		private bool _Available;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDonateIDChanging(int value);
    partial void OnDonateIDChanged();
    partial void OnAmountChanging(int value);
    partial void OnAmountChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnBloodTypeChanging(global::bbFiles.BloodTypes value);
    partial void OnBloodTypeChanged();
    partial void OnRhMarkerChanging(bool value);
    partial void OnRhMarkerChanged();
    partial void OnDonorPESELChanging(long value);
    partial void OnDonorPESELChanged();
    partial void OnAvailableChanging(bool value);
    partial void OnAvailableChanged();
    #endregion
		
		public Donates()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonateID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DonateID
		{
			get
			{
				return this._DonateID;
			}
			set
			{
				if ((this._DonateID != value))
				{
					this.OnDonateIDChanging(value);
					this.SendPropertyChanging();
					this._DonateID = value;
					this.SendPropertyChanged("DonateID");
					this.OnDonateIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Int NOT NULL")]
		public int Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Date NOT NULL")]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BloodType", DbType="Int NOT NULL", CanBeNull=false)]
		public global::bbFiles.BloodTypes BloodType
		{
			get
			{
				return this._BloodType;
			}
			set
			{
				if ((this._BloodType != value))
				{
					this.OnBloodTypeChanging(value);
					this.SendPropertyChanging();
					this._BloodType = value;
					this.SendPropertyChanged("BloodType");
					this.OnBloodTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RhMarker", DbType="Bit NOT NULL")]
		public bool RhMarker
		{
			get
			{
				return this._RhMarker;
			}
			set
			{
				if ((this._RhMarker != value))
				{
					this.OnRhMarkerChanging(value);
					this.SendPropertyChanging();
					this._RhMarker = value;
					this.SendPropertyChanged("RhMarker");
					this.OnRhMarkerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonorPESEL", DbType="BigInt NOT NULL")]
		public long DonorPESEL
		{
			get
			{
				return this._DonorPESEL;
			}
			set
			{
				if ((this._DonorPESEL != value))
				{
					this.OnDonorPESELChanging(value);
					this.SendPropertyChanging();
					this._DonorPESEL = value;
					this.SendPropertyChanged("DonorPESEL");
					this.OnDonorPESELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Available", DbType="Bit NOT NULL")]
		public bool Available
		{
			get
			{
				return this._Available;
			}
			set
			{
				if ((this._Available != value))
				{
					this.OnAvailableChanging(value);
					this.SendPropertyChanging();
					this._Available = value;
					this.SendPropertyChanged("Available");
					this.OnAvailableChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
