//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbFiles.Entities
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Acceptor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Acceptor()
        {
            this.Orders = new ObservableCollection<Order>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address_Street { get; set; }
        public string Address_City { get; set; }
        public string Address_PostalCode { get; set; }
        public string Contact_Phone { get; set; }
        public string Contact_Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Order> Orders { get; set; }
        public virtual User User { get; set; }
    }
}
