//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbFiles.Entities
{
    using System;
    using System.Collections.ObjectModel;
    /// <exclude />
    public partial class Donate
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public bool Avaliable { get; set; }
        public System.DateTime DonateDate { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Donor_PESEL { get; set; }
    
        public virtual Donor Donor { get; set; }
        public virtual Order Order { get; set; }
    }
}
