//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbFiles.Entities
{
    using System;
    using System.Collections.ObjectModel;
    /// <exclude />
    public partial class Donor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Donor()
        {
            this.Donates = new ObservableCollection<Donate>();
        }
    
        public string PESEL { get; set; }
        public string Firstname { get; set; }
        public string Surname { get; set; }
        public string Address_Street { get; set; }
        public string Address_City { get; set; }
        public string Address_PostalCode { get; set; }
        public string Contact_Phone { get; set; }
        public string Contact_Email { get; set; }
        public bbFiles.BloodType Blood_Type { get; set; }
        public bool Blood_RhMarker { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Donate> Donates { get; set; }
    }
}
