//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbFiles.Entities
{
    using System;
    using System.Collections.ObjectModel;
    /// <exclude />
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Send = false;
            this.Donates = new ObservableCollection<Donate>();
        }
    
        public int Id { get; set; }
        public System.DateTime OrderDate { get; set; }
        public bbFiles.BloodType Blood_Type { get; set; }
        public bool Blood_RhMarker { get; set; }
        public int Amount { get; set; }
        public bool Send { get; set; }
        public int AcceptorId { get; set; }
    
        public virtual Acceptor Acceptor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Donate> Donates { get; set; }
    }
}
