//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bbFiles.Entities
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Statistic
    {
        public bbFiles.BloodTypeMarker BloodType { get; set; }
        public long TotalAmount { get; set; }
    }
}
